library(data.table)
data <- read.table(file = "household_power_consumption.txt",header = TRUE,sep = ";",na.strings = "?")
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data <- subset(data,Date >= "2007-02-01" & Date <= "2007-02-02")
data$datetime <- strptime(paste(data$Date, data$Time), "%Y-%m-%d %H:%M:%S")
hist(data$Global_active_power,col = "red",main = "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.copy(device = png, file = "plot1.png", height = 480 , width = 480)
dev.off()
