library(data.table)
data <- read.table(file = "household_power_consumption.txt",header = TRUE,sep = ";",na.strings = "?")
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data <- subset(data,Date >= "2007-02-01" & Date <= "2007-02-02")
data$datetime <- strptime(paste(data$Date, data$Time), "%Y-%m-%d %H:%M:%S")
data$datetime <- as.POSIXct(data$datetime)
with(data, plot(datetime,Global_active_power,type = "l",xlab = "",ylab = "Global Active Power (kilowatts)"))
dev.copy(device = png,file = "plot2.png",width = 480 , height = 480)
dev.off()